GET http://localhost:3000/contacts
GET http://localhost:3000/contacts/69fea616a0368e6c459121a4
GET http://localhost:3000/contacts/69fea646a0368e6c459121a5
GET http://localhost:3000/contacts/69fea676a0368e6c459121a6

POST http://localhost:3000/contacts/ HTTP/1.1
content-type: application/json

{
    "firstName": "The",
    "lastName": "Man",
    "email": "theman@test.com",
    "favoriteColor": "Slate",
    "birthday": "01/01/2003"
}

PUT http://localhost:3000/contacts/69fea616a0368e6c459121a4 HTTP/1.1
content-type: application/json

{
    "firstName": "Kyle",
    "lastName": "Bowser",
    "email": "kyle.bowser@test.com",
    "favoriteColor": "ruby",
    "birthday": "1990-02-02"
}

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@test.com",
    "favoriteColor": "yellow",
    "birthday": "1991-03-03"
}

{
    "firstName": "Jane",
    "lastName": "Dover",
    "email": "jane.dover@test.com",
    "favoriteColor": "charcol",
    "birthday": "1998-08-02"
}

DELETE http://localhost:3000/contacts/6a03c15842ac7e56b4885d6a HTTP/1.1